apiVersion: apps/v1
kind: Deployment
metadata:
  name: homegenie-backend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: backend
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        env:
        - name: LOG_LEVEL
          value: "debug"
        - name: ENVIRONMENT
          value: "development"
        # Enable development features
        - name: DEBUG_MODE
          value: "true"
        - name: HOT_RELOAD
          value: "true"
        # Relaxed timeouts for debugging
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 18  # Allow up to 3 minutes for startup
      # Remove init container for faster development cycles
      initContainers: []