apiVersion: apps/v1
kind: Deployment
metadata:
  name: homegenie-frontend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: frontend
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: NODE_ENV
          value: "development"
        - name: REACT_APP_API_URL
          value: "http://homegenie.local/api"
        - name: REACT_APP_DEBUG
          value: "true"
        # Relaxed health checks for development
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5