apiVersion: v1
kind: Secret
metadata:
  name: homegenie-secrets
  namespace: homegenie
  labels:
    app.kubernetes.io/name: homegenie
    app.kubernetes.io/instance: homegenie
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Database credentials
  DB_PASSWORD: "your-secure-database-password"
  DATABASE_URL: "postgresql://homegenie:your-secure-database-password@postgres:5432/homegenie"
  
  # Application secrets
  JWT_SECRET: "your-super-secret-jwt-key-minimum-32-characters-long"
  
  # Optional: SMTP configuration
  SMTP_PASSWORD: "your-smtp-app-password"
  
  # Optional: Redis password
  REDIS_PASSWORD: "your-redis-password"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: homegenie
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: homegenie-postgres
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_DB: "homegenie"
  POSTGRES_USER: "homegenie"
  POSTGRES_PASSWORD: "your-secure-database-password"

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: homegenie
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: homegenie-redis
    app.kubernetes.io/component: cache
type: Opaque
stringData:
  REDIS_PASSWORD: "your-redis-password"