# HomeGenie Development Docker Compose
version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - API_PORT=8080
      - API_HOST=0.0.0.0
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=homegenie
      - DB_USER=homegenie
      - DB_PASSWORD=password
      - JWT_SECRET=dev-jwt-secret-key-32-chars-min
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
    depends_on:
      - postgres
      - redis
    networks:
      - homegenie

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - homegenie

  # Database
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=homegenie
      - POSTGRES_USER=homegenie
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - homegenie

  # Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - homegenie

volumes:
  postgres_data:
  redis_data:

networks:
  homegenie:
    driver: bridge